### PR TITLE
Document Armbian Support For LicheePi 4A

### PR DESCRIPTION
**Pull request by Kreyren**

### CODE REVIEW

**Comment by chainsx** [comment]
I think the content of this document is inappropriate and cannot be merged.
@wonderfullook

**Comment by chainsx** [comment]
I think an interface related to usage should be created on the Armbian official website, such as: https://www.armbian.com/rock-5b.
However, the construction steps for Armbian can be obtained from the Armbian documentation, which would be a bit redundant if placed here again.

**Comment by chainsx** [comment]
And I'm very sorry about the fact that I found that the instructions on usage in your document were completely incorrect.

**Comment by Kreyren** [comment]
> I think an interface related to usage should be created on the Armbian official website, such as: https://www.armbian.com/rock-5b. However, the construction steps for Armbian can be obtained from the Armbian documentation, which would be a bit redundant if placed here again.  -- @chainsx (https://github.com/sipeed/sipeed_wiki/pull/512#issuecomment-1679457198)

Agree, this is not supposed to be a replacement of armbian docs, but more like quick reference on where to find help and generic idea on how to build the image while referring to the armbian docs for more info so that when people search though sipeed wiki to know that armbian is an option and +- how it works and in what state it is so that they can decide whether they want to use it or not.

Beyond that i agree that armbian website is better place for it such as how i manage https://www.armbian.com/olimex-teres-a64, though i would avoid linking to the armbian docs in https://docs.armbian.com as those are written to be very generic and cover lot of scenarios (while also being in a need of rewriting) so these tend to confuse users who don't have background in working with the board, but are quite useful for advanced users and developers.

**Comment by taorye** [comment]
> I think the content of this document is inappropriate and cannot be merged. @wonderfullook

@wonderfullook is gone, we will miss him.

**Comment by chainsx** [comment]
> > I think the content of this document is inappropriate and cannot be merged. @wonderfullook
> 
> @wonderfullook is gone, we will miss him.

额，这老早老早之前的事了

**Comment by chainsx** [comment]
把这个 PR 强制关了吧，挂着没意思

**Pull request closed without merging**
